<template>
  <section id="home-view">
    <div>top</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>index page</div>
    <div>end</div>
  </section>
</template>

<script>
export default {
  name: 'HomePage',
  layout: 'parallax',
  components: {},
}
</script>

<style scoped>
</style>
